post_pkg_postinst() {
	case "${CATEGORY}/${PN}" in
		*/cryptsetup | */lvm2 | */ntp | acct-*/* )
			:;
			;;
		*)
			s6-sv-hook -i "${PN}" || true
			;;
	esac	
}

post_pkg_postrm() {
	case "${CATEGORY}/${PN}" in
		*/cryptsetup | */lvm2 | */ntp | acct-*/* )
			:;
			;;
		*)
			s6-sv-hook -r "${PN}" || true
			;;
	esac	
}

