storelist = /home/USER/.config/s6/sv
scandir = /home/USER/.config/s6/service
livedir = /home/USER/.config/s6/db/live/s6-rc
repodir = /home/USER/.config/s6/repo
bootdb = /home/USER/.config/s6/db/boot/compiled
